language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
    - npm
    - squid
    - curl
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono:
  - 4.0.5
os:
  - linux
  # - osx CoreCLR tests time out too frequently on OSX to be useful.
#osx_image: xcode7.1
branches:
  only:
    - master
    #- release
    #- dev
    #- /^(.*\/)?ci-.*$/
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
before_script:
  - npm install -g bower
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - chmod +x ./build.sh  
  - ./build.sh
after_success:
  -  curl --data-binary '{"text":"Build successful"}'  'http://integram.org/cU5CLpMbNcR'
after_failure:
  -  curl --data-binary '{"text":"Build FAILED 🙀"}'  'http://integram.org/cU5CLpMbNcR'